### PR TITLE
Configuration options for prover/coordinator

### PR DESCRIPTION
**Pull request by pinkiebell**
Add the following features:
###### coordinator
- `unsafe_rpc` option for the coordinator. To guard methods like `config`
- `mock_prover_if_error` option. Defaults to true and runs the mock prover if the real prover fails.
- Add uniform `config` rpc method to get/set the coordinator configuration.
  Not all config options are being reflected yet.
###### prover
- Add `mock_feedback` to `ProofRequestOptions. If true, runs the MockProver if proofing fails.

Fixes: #80
Related: #58

### CODE REVIEW

**Comment by AronisAt79** [comment]
@pinkiebell 
regarding:
 "[coordinator: support get/set config](https://github.com/privacy-scaling-explorations/zkevm-chain/pull/81/commits/3e8251b0a8dad890631c9c07363b9893e94f16ac)"

Do we now use the same rpc method to query the node for existing config and setting up conf parameters as well? If so, can you please explain what are the inputs in case of get config?

p.s. previously i was using the get_config method which now returns error: method does not exist.

thanks,
Marios

**Comment by pinkiebell** [comment]
> @pinkiebell regarding: "[coordinator: support get/set config](https://github.com/privacy-scaling-explorations/zkevm-chain/pull/81/commits/3e8251b0a8dad890631c9c07363b9893e94f16ac)"
> 
> Do we now use the same rpc method to query the node for existing config and setting up conf parameters as well? If so, can you please explain what are the inputs in case of get config?
> 
> p.s. previously i was using the get_config method which now returns error: method does not exist.
> 
> thanks, Marios

Yes, this was unified. The method is just `config` now and if called without any arguments it returns the config and otherwise expects the config object as parameter if you want to change the config.

**Comment by AronisAt79** [comment]
> if called without any arguments

Thanks @Pinkie, does this mean we need to provide an empty struct , an empty params array or no params at all:

With empty params i get:

'{"jsonrpc":"2.0","id": 1, "method": "config", "params":[]}'
<Response [200]>
{'error': {'code': -32000, 'message': 'expected struct CoordinatorConfig'},
 'id': 1,
 'jsonrpc': '2.0'}

while if i provide an empty struct:

'{"jsonrpc":"2.0","id": 1, "method": "config", "params":[{}]}'
<Response [200]>
{'error': {'code': -32000, 'message': 'missing field `dummy_proof`'},
 'id': 1,
 'jsonrpc': '2.0'}

**Comment by pinkiebell** [comment]
> Config method returns the following:
> 
> '{"jsonrpc":"2.0","id": 1, "method": "config", "params":[]}' <Response [200]> {'error': {'code': -32000, 'message': 'this method is disabled'}, 'id': 1, 'jsonrpc': '2.0'}

You have to enable unsafe methods now, [see here](https://github.com/privacy-scaling-explorations/zkevm-chain/pull/81/files#diff-7d475402712ae0c8d9ec2633c3a58cba3f4a1f1cf270438f1ce3b73e238133ebR72)

**Comment by pinkiebell** [comment]
> thanks @pinkiebell. I added the environmentals to the coordinator service in compose file. Is it on purpose to only include them in the dev service?

Yes, I didn't want to expose those on default. But I will add `.env` support. That will be easier to change :)

> I now can "get config" but setting seems to not work. This is an example payload but it seems the config is not affected. Setting dummy_prover to True does not suppress proofRequests for new blocks. I thinks previously this worked with dummy_proof parameter
> 
> {"jsonrpc":"2.0","id": 1, "method": "config", "params": [{"dummy_prover":True,"mock_prover":false,"mock_prover_if_error":false,"unsafe_rpc":false}]}

It seems like `True` is the same as `false`, must be the way serde is handling this or it may have something todo with the clap helpers. Anyway, `True` is indeed invalid - should be `true`.

**Review by AronisAt79 — APPROVED** [review]
nice to have: make 'set config' parameters optional instead of having to provide all values. Otherwise it LGTM

**Comment by pinkiebell** [comment]
> Thanks for the hints @pinkiebell.
> Just a nice to have note; could we make the config method parameters optional, instead of having to provide all values for 'set_config'? We can open a new issue for this one if you think it makes sense.
> otherwise it LGTM.

Making it optional needs more manual plumbing but can be done. The best way is to retrieve the current config, update some fields and then set the new config. That way you don't have to know all required fields in advance 👌

**Comment by AronisAt79** [comment]
> The best way is to retrieve the current config, update some fields and then set the new config. That way you don't have to know all required fields in advance

Nice one! I will modify my method to handle 'set config' like that !

**Pull request merged**
